### PR TITLE
Topic/grid montage collection methods

### PR DESCRIPTION
**Pull request by joeykleingers**
Added Row-By-Row, Column-By-Column, Snake By Rows, and Snake By Columns collection methods when creating a grid montage.

### CODE REVIEW

**Review by mmarineBlueQuartz — CHANGES_REQUESTED** [review]
You forgot break statements in the switch.

I don't believe you need the extra set of curly brackets after each case.  It's only required to get around unscoped variable creation, which isn't allowed syntactically inside a switch because cases are not individually scoped to prevent variables from flowing from one to the next.  If you don't need the curly brackets there for a workaround (which is a code smell to begin with), don't use them.

Rather than RowByRow, use CombByRows like you did for Snake.  Also, do we ever snake by columns?  That seems inconsistent with DREAM.3D, where we only ever seem to worry about Comb vs Snake order along rows.  If there isn't, leave it as CombOrder and SnakeOrder as the only options.

**Comment by joeykleingers** [comment]
Someone who wants to create a grid montage may have data that was originally collected using SnakeByColumns, so I threw it in there as an option in case someone needs to use it.  I know we don't use it right now, but a third party developer may in their own filter.

**Comment by joeykleingers** [comment]
Also, should we have variations where montage data could have been collected from front to back and from back to front (depth variation?). Right now I just assume that they are collecting from front to back.  Although then that brings up the question of what do you call each variation because you can have CombByRows (front to back), Comb By Rows (back to front), Snake By Rows (front to back), etc etc.

**Comment by mmarineBlueQuartz** [comment]
It's literally the order of names in a list, and we have a FilterParameter that can generate SnakeOrder and CombOrder lists from the name-based ordering we have been reliant on.  If someone is handling non-standard data and wants to create a filter to handle it, it's on them to find a way to bring it in line with everything else in the pipeline.  (Row-based) Comb and Snake order is enough.  Special cases can be handled like special cases when and where they occur.

**Comment by joeykleingers** [comment]
It's not giving me the option re-request a review, but I'm ready for it.

**Review by mmarineBlueQuartz — CHANGES_REQUESTED** [review]
Change CombByRows to CombOrder and SnakeByRows to SnakeOrder and I'll merge it in.

**Comment by joeykleingers** [comment]
Done.

**Pull request merged**
